package cencosud.poccencoregla;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ventas implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Ventas() {
    }

}