package cencosud.poccencoregla;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Venta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ventaMensual")
   private java.lang.Integer ventaMensual;
   @org.kie.api.definition.type.Label("VentaComercial")
   private java.lang.Integer ventaComercial;
   @org.kie.api.definition.type.Label("Diferencia")
   private java.lang.Integer diferencia;
   @org.kie.api.definition.type.Label("MetaObjetivo")
   private java.lang.Integer metaObjetivo;
   @org.kie.api.definition.type.Label("Premio")
   private java.lang.Integer premio;
   @org.kie.api.definition.type.Label("RentaBruta")
   private java.lang.Integer rentaBruta;
   @org.kie.api.definition.type.Label("Cargo")
   private java.lang.String cargo;
   @org.kie.api.definition.type.Label("RentaTotal")
   private java.lang.Integer rentaTotal;
   @org.kie.api.definition.type.Label("PorcentajePremio")
   private java.lang.Integer porcentajePremio;

   @org.kie.api.definition.type.Label("Porcentaje Por Cargo")
   private java.lang.Double porcetajePorCargo;

   @org.kie.api.definition.type.Label(value = "Antiguedad Local")
   private int antiguedadLocal;

   public Venta()
   {
   }

   public java.lang.Integer getVentaMensual()
   {
      return this.ventaMensual;
   }

   public void setVentaMensual(java.lang.Integer ventaMensual)
   {
      this.ventaMensual = ventaMensual;
   }

   public java.lang.Integer getVentaComercial()
   {
      return this.ventaComercial;
   }

   public void setVentaComercial(java.lang.Integer ventaComercial)
   {
      this.ventaComercial = ventaComercial;
   }

   public java.lang.Integer getDiferencia()
   {
      return this.diferencia;
   }

   public void setDiferencia(java.lang.Integer diferencia)
   {
      this.diferencia = diferencia;
   }

   public java.lang.Integer getMetaObjetivo()
   {
      return this.metaObjetivo;
   }

   public void setMetaObjetivo(java.lang.Integer metaObjetivo)
   {
      this.metaObjetivo = metaObjetivo;
   }

   public java.lang.Integer getPremio()
   {
      return this.premio;
   }

   public void setPremio(java.lang.Integer premio)
   {
      this.premio = premio;
   }

   public java.lang.Integer getRentaBruta()
   {
      return this.rentaBruta;
   }

   public void setRentaBruta(java.lang.Integer rentaBruta)
   {
      this.rentaBruta = rentaBruta;
   }

   public java.lang.String getCargo()
   {
      return this.cargo;
   }

   public void setCargo(java.lang.String cargo)
   {
      this.cargo = cargo;
   }

   public java.lang.Integer getRentaTotal()
   {
      return this.rentaTotal;
   }

   public void setRentaTotal(java.lang.Integer rentaTotal)
   {
      this.rentaTotal = rentaTotal;
   }

   public java.lang.Integer getPorcentajePremio()
   {
      return this.porcentajePremio;
   }

   public void setPorcentajePremio(java.lang.Integer porcentajePremio)
   {
      this.porcentajePremio = porcentajePremio;
   }

   public java.lang.Double getPorcetajePorCargo()
   {
      return this.porcetajePorCargo;
   }

   public void setPorcetajePorCargo(java.lang.Double porcetajePorCargo)
   {
      this.porcetajePorCargo = porcetajePorCargo;
   }

   public int getAntiguedadLocal()
   {
      return this.antiguedadLocal;
   }

   public void setAntiguedadLocal(int antiguedadLocal)
   {
      this.antiguedadLocal = antiguedadLocal;
   }

   public Venta(java.lang.Integer ventaMensual, java.lang.Integer ventaComercial,
         java.lang.Integer diferencia, java.lang.Integer metaObjetivo,
         java.lang.Integer premio, java.lang.Integer rentaBruta,
         java.lang.String cargo, java.lang.Integer rentaTotal,
         java.lang.Integer porcentajePremio, java.lang.Double porcetajePorCargo,
         int antiguedadLocal)
   {
      this.ventaMensual = ventaMensual;
      this.ventaComercial = ventaComercial;
      this.diferencia = diferencia;
      this.metaObjetivo = metaObjetivo;
      this.premio = premio;
      this.rentaBruta = rentaBruta;
      this.cargo = cargo;
      this.rentaTotal = rentaTotal;
      this.porcentajePremio = porcentajePremio;
      this.porcetajePorCargo = porcetajePorCargo;
      this.antiguedadLocal = antiguedadLocal;
   }

}