package cencosud.poccencoregla;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ventas implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Venta Neta")
   private java.lang.Integer ventaNeta;
   @org.kie.api.definition.type.Label("Venta Area Comercia")
   private java.lang.Integer ventaAreaComercia;
   @org.kie.api.definition.type.Label("Presupuesto")
   private java.lang.Integer presupuesto;
   @org.kie.api.definition.type.Label("Plan De Metas")
   private java.lang.Integer planDeMeta;
   @org.kie.api.definition.type.Label("Antiguedad Local")
   private java.lang.Integer antiguedaLocal;
   @org.kie.api.definition.type.Label("Renta Bruta")
   private java.lang.Integer rentaBruta;
   @org.kie.api.definition.type.Label("Porcentaje a Pajar")
   private java.lang.Integer porcentajeCumplimiento;
   @org.kie.api.definition.type.Label("Variacion Minima")
   private java.lang.Integer variacionMinima;
   @org.kie.api.definition.type.Label("Variacion Maxima")
   private java.lang.Integer variacionMaxima;
   @org.kie.api.definition.type.Label("Rut")
   private java.lang.Integer rut;
   @org.kie.api.definition.type.Label("Monto")
   private java.lang.Integer monto;

   @org.kie.api.definition.type.Label("Cargo")
   private java.lang.String cargo;

   @org.kie.api.definition.type.Label(value = "% por cargo")
   private java.lang.Integer porcentajePorcargo;

   public Ventas()
   {
   }

   public java.lang.Integer getVentaNeta()
   {
      return this.ventaNeta;
   }

   public void setVentaNeta(java.lang.Integer ventaNeta)
   {
      this.ventaNeta = ventaNeta;
   }

   public java.lang.Integer getVentaAreaComercia()
   {
      return this.ventaAreaComercia;
   }

   public void setVentaAreaComercia(java.lang.Integer ventaAreaComercia)
   {
      this.ventaAreaComercia = ventaAreaComercia;
   }

   public java.lang.Integer getPresupuesto()
   {
      return this.presupuesto;
   }

   public void setPresupuesto(java.lang.Integer presupuesto)
   {
      this.presupuesto = presupuesto;
   }

   public java.lang.Integer getPlanDeMeta()
   {
      return this.planDeMeta;
   }

   public void setPlanDeMeta(java.lang.Integer planDeMeta)
   {
      this.planDeMeta = planDeMeta;
   }

   public java.lang.Integer getAntiguedaLocal()
   {
      return this.antiguedaLocal;
   }

   public void setAntiguedaLocal(java.lang.Integer antiguedaLocal)
   {
      this.antiguedaLocal = antiguedaLocal;
   }

   public java.lang.Integer getRentaBruta()
   {
      return this.rentaBruta;
   }

   public void setRentaBruta(java.lang.Integer rentaBruta)
   {
      this.rentaBruta = rentaBruta;
   }

   public java.lang.Integer getPorcentajeCumplimiento()
   {
      return this.porcentajeCumplimiento;
   }

   public void setPorcentajeCumplimiento(
         java.lang.Integer porcentajeCumplimiento)
   {
      this.porcentajeCumplimiento = porcentajeCumplimiento;
   }

   public java.lang.Integer getVariacionMinima()
   {
      return this.variacionMinima;
   }

   public void setVariacionMinima(java.lang.Integer variacionMinima)
   {
      this.variacionMinima = variacionMinima;
   }

   public java.lang.Integer getVariacionMaxima()
   {
      return this.variacionMaxima;
   }

   public void setVariacionMaxima(java.lang.Integer variacionMaxima)
   {
      this.variacionMaxima = variacionMaxima;
   }

   public java.lang.Integer getRut()
   {
      return this.rut;
   }

   public void setRut(java.lang.Integer rut)
   {
      this.rut = rut;
   }

   public java.lang.Integer getMonto()
   {
      return this.monto;
   }

   public void setMonto(java.lang.Integer monto)
   {
      this.monto = monto;
   }

   public java.lang.String getCargo()
   {
      return this.cargo;
   }

   public void setCargo(java.lang.String cargo)
   {
      this.cargo = cargo;
   }

   public java.lang.Integer getPorcentajePorcargo()
   {
      return this.porcentajePorcargo;
   }

   public void setPorcentajePorcargo(java.lang.Integer porcentajePorcargo)
   {
      this.porcentajePorcargo = porcentajePorcargo;
   }

   public Ventas(java.lang.Integer ventaNeta, java.lang.Integer ventaAreaComercia,
         java.lang.Integer presupuesto, java.lang.Integer planDeMeta,
         java.lang.Integer antiguedaLocal, java.lang.Integer rentaBruta,
         java.lang.Integer porcentajeCumplimiento,
         java.lang.Integer variacionMinima, java.lang.Integer variacionMaxima,
         java.lang.Integer rut, java.lang.Integer monto, java.lang.String cargo,
         java.lang.Integer porcentajePorcargo)
   {
      this.ventaNeta = ventaNeta;
      this.ventaAreaComercia = ventaAreaComercia;
      this.presupuesto = presupuesto;
      this.planDeMeta = planDeMeta;
      this.antiguedaLocal = antiguedaLocal;
      this.rentaBruta = rentaBruta;
      this.porcentajeCumplimiento = porcentajeCumplimiento;
      this.variacionMinima = variacionMinima;
      this.variacionMaxima = variacionMaxima;
      this.rut = rut;
      this.monto = monto;
      this.cargo = cargo;
      this.porcentajePorcargo = porcentajePorcargo;
   }

}